### PR TITLE
Refactor Linux Driver

### PR DESCRIPTION
**Pull request by thirtytwobits**
I did a similar refactor downstream to support a posix-like RTOS
internally. I'm submitting this but with our RTOS-specific driver
removed to allow Peter to refactor his nuttx driver to share most
of its implementation with linux.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Why did you remove the LPC11C24 driver?

**Comment by pavel-kirienko** [comment]
Actually, none of the platform drivers should be here anyway. I suggest moving this changeset over to https://github.com/UAVCAN/platform_specific_components/tree/legacy-v0/linux/libuavcan.

**Comment by thirtytwobits** [comment]
> Why did you remove the LPC11C24 driver?

It seemed incredibly out of date. When's the last time anyone actually verified this worked? I can add it back but is it at all relevant at this point?

**Comment by pavel-kirienko** [comment]
It is certainly not out of date and it is actually used in OpenGrab EPM v3, for example. If it's not being updated it doesn't mean that it's dead, it's just finished and there's nothing else to change.

**Comment by pavel-kirienko** [comment]
Closing due to #307.

**Pull request closed without merging**
