### PR TITLE
kinetis:UAVCAN driver

### PR DESCRIPTION
**Pull request by davids5**
Hi Pavel,

This add the FlexCAN driver for uavcan. I have more testing to do but it is communicating. I still have to code the filters.

### CODE REVIEW

**Comment by thirtytwobits** [comment]
Super cool to see Kinetis support. Being just north of Portland we love us some Teensy up here in Seattle.

@pavel-kirienko Do we want to break this out into a libuavcan_flexcan repo to match our new driver pattern?

**Comment by pavel-kirienko** [comment]
> Do we want to break this out into a libuavcan_flexcan repo to match our new driver pattern?

Yes, we do. Could you take care of that, please? This PR should be closed then.

**Comment by pavel-kirienko** [comment]
@davids5 could you please remove my copyrights from the contributed code.

**Comment by davids5** [comment]
@pavel-kirienko will do did you want an attribution or should I switch it to all PX4?

**Comment by pavel-kirienko** [comment]
Since I wrote none of that code, please do not mention me there. You can use PX4 or whatever you find appropriate.

**Comment by davids5** [comment]
@thirtytwobits, @pavel-kirienko I will force push the changes today.

**Comment by davids5** [comment]
@pavel-kirienko per our discussion, that the code was based on your stm32 work, the  copyrights are updated.

**Comment by thirtytwobits** [comment]
@davids5 let me create a new repository for you to push to. Do you mind holding off on this change and starting the flexcan support over in the other repo? Sorry but we're doing this new multi-repo thing with the drivers so we still figuring out the full driver build story.

**Comment by davids5** [comment]
@thirtytwobits - I am on a deadline for the integration of this Kinetis driver into master on PX4 for the NXPhlite board. I will need to have this be a smooth transition with few moving parts and no unrelated road blocks.

**Comment by pavel-kirienko** [comment]
> I am on a deadline for the integration of this Kinetis driver into master on PX4 for the NXPhlite board.

The deadline is ill-defined then; we no longer keep drivers in master, they are kept in their separate repositories. Moving to a new repo should not introduce any additional delays; rather it should simplify maintenance and speed up development.

**Comment by davids5** [comment]
@pavel-kirienko - Ok that is new information to me. I branched PX4's libuavcan and did the work in that structure. What is the plan for PX4 master being moved to the new structure?

**Comment by pavel-kirienko** [comment]
I hadn't realized there's a PX4 fork of the library.

> What is the plan for PX4 master being moved to the new structure?

The best plan is no plan at all - I have no idea. Perhaps it should be updated when UAVCAN v1.0 is out?

**Comment by davids5** [comment]
It is not a fork, it was upstream 2-3 commits back of master in the repo that PX4 was tied to when I started to add the driver. NXPhlite needs to be finished probably before UAVCAN v1.0 is done (Like today or tomorrow).  I am trying to get that done, hence my original post. I am trying to avoid 2 migrations. I do not want to have the NXPhlite branch of nuttx change or add more than the kinetis board. It seems that decoupling this would make more sense for both projects.  But tell me what you want done.

**Comment by pavel-kirienko** [comment]
I just created this: https://github.com/UAVCAN/libuavcan_kinetis

@davids5 please move your driver over there; use this as an example if necessary: https://github.com/UAVCAN/libuavcan_lpc11c24. If you could provide a few lines of usage information in the readme that would be awesome. Thanks!

**Comment by pavel-kirienko** [comment]
Closing because the driver seems to have been migrated. Please reopen if it's still needed.

**Comment by pavel-kirienko** [comment]
Merging as a temporary solution to PX4-specific issues. This seems acceptable because the master branch here still contains the other drivers; they will be removed later when v1.0 is merged. PX4 should adopt the new driver dependencies by then.

**Pull request merged**
