### PR TITLE
Many fixes to CMakeLists and dsdl compiler

### PR DESCRIPTION
**Pull request by thirtytwobits**
Modenizing the build script and making the dsdl compiler more flexible.

The change can't actually compile generated dsdl (still missing the
marshal classes) but it does successfully generate the dsdl types and
the make command succeeds.

Also: I say "submodules" in this PR because in the next one I want to pull dsdl in as a submodule instead of as a recursive submodule. Recursive submodules considered harmful.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Pyuavcan is no longer needed for parsing DSDL. Please use pydsdl instead: https://github.com/UAVCAN/pydsdl

**Comment by thirtytwobits** [comment]
> Pyuavcan is no longer needed for parsing DSDL. Please use pydsdl instead: https://github.com/UAVCAN/pydsdl

Oh, is that ready? The build is failing and we aren't done writing the specification so I just assumed it wasn't ready to use.

**Comment by thirtytwobits** [comment]
Okay. Going to close this while I retool to use pydsdl

**Comment by pavel-kirienko** [comment]
> Oh, is that ready? The build is failing and we aren't done writing the specification so I just assumed it wasn't ready to use.

It is as ready as a release labeled v0.3 can be. I just fixed the build and merged my last set of sweeping changes into the DSDL repo, everything should be working now. Make extra sure that you are basing your DSDL submodule on the `uavcan-v1.0` branch (it will replace master when we're done).

**Pull request closed without merging**
