### PR TITLE
Issue #100 remove auto_ptr and c++03 support.

### PR DESCRIPTION
**Pull request by thirtytwobits**
Problem:
auto_ptr is deprecated.

Solution:
use unique_ptr which is only available in c++11 and newer.
Also fix how unit tests are run as part of the build to keep them from being
deleted when they fail.

Testing:
Unit tests on linux run.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Good to merge?

**Comment by thirtytwobits** [comment]
Let's wait until #142 is merged then I'll get this one green.

**Comment by thirtytwobits** [comment]
This is ready now.

**Comment by pavel-kirienko** [comment]
Thanks, Scott!

**Pull request merged**
