### PR TITLE
Update stm32 drivers to ChibiOS 3.0

### PR DESCRIPTION
**Pull request by antoinealb**
I don't know if there is a desire to keep ChibiOS 2.6 around in tree. This PR simply replaces the old implementation with the new API. I did not change the example as I don't have a way to test it.

@nuft Looks OK for you ?

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Folks, I've got fond feelings for ChibiOS v2.6. Can you add some preprocessor trickery to maintain compatibility please? I'll test it on my hardware then and merge once you consider it finished.

**Comment by antoinealb** [comment]
Ok, we can do something using `CH_KERNEL_MAJOR`.

**Comment by antoinealb** [comment]
@pavel-kirienko @nuft updated pull request with ChibiOS 2 compatibility.

**Comment by nuft** [comment]
Normally it should work with ChibiOS 2. I dindn't thoroughly test it though.

**Comment by antoinealb** [comment]
@pavel-kirienko can you test it on your setup and merge if it works ?

**Comment by pavel-kirienko** [comment]
Tested on my demoboard, seems to work fine. Thanks, and sorry for the delay.

**Pull request merged**
